import './globals.css';
import AppNavbar from "@/components/AppNavbar";
import React from "react";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}


export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <main>
            <AppNavbar/>
            <div className={"m-10"}>
                {children}
            </div>
        </main>
        </body>
        </html>
    )
}

