import './globals.css';
import AppNavbar from "@/components/AppNavbar";
import React from "react";
import {AppMobileNav} from "@/components/AppMobileNavbar";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}


export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={"dark"}>
        <main>
            <AppNavbar/>
            <div className={"px-2 max-w-3xl ml-auto mr-auto"}>
                {children}
            </div>
        </main>
        </body>
        </html>
    )
}

