services:
  gateway-service:
    image: gateway-service:latest
    hostname: gateway
    networks:
      - budget-tracker-internal
    ports:
      - "8080:8080"
  user-service:
    image: user-service:latest
    hostname: user
    networks:
      - budget-tracker-internal
    ports:
      - "8081:8080"
  email-service:
    image: email-service:latest
    hostname: email
    networks:
      - budget-tracker-internal
    ports:
      - "8082:8080"
networks:
  budget-tracker-internal:
    name: budget-tracker-internal