services:
  gateway-service:
    image: gateway-service:latest
    hostname: gateway
    networks:
      - budget-tracker-internal
    ports:
      - "8080:8080"
networks:
  budget-tracker-internal:
    name: budget-tracker-internal