services:
  database:
    image: postgres:16.4
    hostname: database
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=ChangeMe
      - POSTGRES_DB=budget-tracker
    networks:
      - budget-tracker-internal
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d budget-tracker -U admin"]
      interval: 1s
      timeout: 10s
      retries: 30

  flyway-migrate:
    image: flyway/flyway:10.17
    command: migrate
    networks:
      - budget-tracker-internal
    volumes:
      - ./database/flyway-docker.conf:/flyway/conf/flyway.conf
      - ./database/src/main/resources/migrations/ddl:/flyway/sql
    depends_on:
      database:
        condition: service_healthy

  gateway-service:
    image: gateway-service:latest
    hostname: gateway
    networks:
      - budget-tracker-internal
    environment:
      - SPRING_PROFILES_ACTIVE= docker
      - JAVA_TOOL_OPTIONS= -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:6000
    ports:
      - "8080:8080"
      - "6000:6000"
  user-service:
    image: user-service:latest
    hostname: user
    networks:
      - budget-tracker-internal
    environment:
      - SPRING_PROFILES_ACTIVE= docker
      - JAVA_TOOL_OPTIONS= -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:6000
    ports:
      - "8081:8080"
      - "6001:6000"
  notification-service:
    image: notification-service:latest
    hostname: notification
    networks:
      - budget-tracker-internal
    environment:
      - SPRING_PROFILES_ACTIVE= docker
      - JAVA_TOOL_OPTIONS= -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:6000
    ports:
      - "8083:8080"
      - "6003:6000"
  email-service:
    image: email-service:latest
    hostname: email
    networks:
      - budget-tracker-internal
    environment:
      - SPRING_PROFILES_ACTIVE= docker
      - JAVA_TOOL_OPTIONS= -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:6000
    ports:
      - "8082:8080"
      - "6002:6000"
  budget-service:
    image: budget-service:latest
    hostname: budget
    networks:
      - budget-tracker-internal
    environment:
      - SPRING_PROFILES_ACTIVE= docker
      - JAVA_TOOL_OPTIONS= -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:6000
    ports:
      - "8084:8080"
      - "6004:6000"
  calculation-service:
    image: calculation-service:latest
    hostname: calculation
    networks:
      - budget-tracker-internal
    environment:
      - SPRING_PROFILES_ACTIVE= docker
      - JAVA_TOOL_OPTIONS= -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:6000
    ports:
      - "8085:8080"
      - "6005:6000"
networks:
  budget-tracker-internal:
    name: budget-tracker-internal
