import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Layout} from "antd";
import {Content, Header} from "antd/lib/layout/layout";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Layout>
            <Header className={"text-white"}>
               <Link href={'/'}>Songs Site</Link>
            </Header>
            <Layout className={"px-4 pt-4 bg-white"}>
                <Content className={"p-3 bg-gray-200 rounded-md"}>
                    {children}
                </Content>
            </Layout>
        </Layout>

      </body>
    </html>
  );
}
